version: '3.8'

services:
  wordpress:
    image: ben2511/resumne:latest
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${{ secrets.WORDPRESS_DB_HOST }}
      WORDPRESS_DB_USER: ${{ secrets.WORDPRESS_DB_USER }}
      WORDPRESS_DB_PASSWORD: ${{ secrets.WORDPRESS_DB_PASSWORD }}
      WORDPRESS_DB_NAME: ${{ secrets.WORDPRESS_DB_NAME }}
    volumes:
      - wordpress_data:/var/www/html

volumes:
  wordpress_data: {}

