version: '3.8'

services:
  wordpress:
    image: ben2511/resumne:latest
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: sql7.freesqldatabase.com
      WORDPRESS_DB_USER: sql7716242
      WORDPRESS_DB_PASSWORD: v9tavbHDSg
      WORDPRESS_DB_NAME: sql7716242
    volumes:
      - wordpress_data:/var/www/html

volumes:
  wordpress_data: {}
