name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      
    - name: Test database connection
      run: |
        mysql --host=${{ secrets.WORDPRESS_DB_HOST }} --user=${{ secrets.WORDPRESS_DB_USER }} --password=${{ secrets.WORDPRESS_DB_PASSWORD }} --database=${{ secrets.WORDPRESS_DB_NAME }} -e "SHOW TABLES;"
      env:
        WORDPRESS_DB_HOST: sql7.freesqldatabase.com
        WORDPRESS_DB_USER: sql7716242
        WORDPRESS_DB_PASSWORD: v9tavbHDSg
        WORDPRESS_DB_NAME: sql7716242

    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PW }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ben2511/resume:latest