name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PW }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ben2511/resumne:latest

    - name: Display environment variables
      run: |
        echo "WORDPRESS_DB_HOST: $WORDPRESS_DB_HOST"
        echo "WORDPRESS_DB_USER: $WORDPRESS_DB_USER"
        echo "WORDPRESS_DB_PASSWORD: $WORDPRESS_DB_PASSWORD"
        echo "WORDPRESS_DB_NAME: $WORDPRESS_DB_NAME"
      env:
        WORDPRESS_DB_HOST: ${{ secrets.WORDPRESS_DB_HOST }}
        WORDPRESS_DB_USER: ${{ secrets.WORDPRESS_DB_USER }}
        WORDPRESS_DB_PASSWORD: ${{ secrets.WORDPRESS_DB_PASSWORD }}
        WORDPRESS_DB_NAME: ${{ secrets.WORDPRESS_DB_NAME }}
